### ISSUE TITLE
Launcher intersecting with panel

### ISSUE THREAD

**Issue by SnoutBug** [SnoutBug/mmcklauncher#6]
The launcher appears to be intersecting the panel its opened from under unknown circumstances

**Comment by GreenTeaSeb** [comment]
As I said before,
Changing
` y = screen.height - fs.height + root.margins.bottom + root.margins.top;`
to
` y = screen.height - fs.height - root.margins.bottom - root.margins.top;`

You need to subtract the y position since it starts in the upper corner, adding onto Y will only make the menu go down.

**Comment by SnoutBug** [comment]
Addressed in release [0.3](https://github.com/SnoutBug/mmcklauncher/releases/tag/0.3)
